### ISSUE TITLE
[Crash] Server Crash with the latest RS version

### ISSUE THREAD

**Issue by BrainInBlack** [Buuz135/RS-Requestify#7]
The recent updates to RS (1.6.13 and 1.6.14) seemed to have changed a few things in the API, causing requests made by this addon to crash the server/client.

https://gist.github.com/BrainInBlack/fa9af312def63dd523153231b75d7daa

**Comment by Norway174** [comment]
Getting the same problem here. Even the same error as posted above, by the looks of it.

Last update was 4 months ago.
Any chance this will get fixed in a timely manner?

**Comment by auddie2015** [comment]
java.lang.NoSuchMethodError: com.raoulvdberge.refinedstorage.api.autocrafting.ICraftingManager.request(Lcom/raoulvdberge/refinedstorage/api/network/node/INetworkNode;Lnet/minecraft/item/ItemStack;I)Lcom/raoulvdberge/refinedstorage/api/autocrafting/task/ICraftingTask;
	at com.buuz135.refinedstoragerequestify.proxy.block.network.NetworkNodeRequester.update(NetworkNodeRequester.java:74)
	at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:23)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_962_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

Refined Storage 1.6.14
Refined Storage Requestify 1.12.2-1.0.01-2
Forge 1.12.2-14.23.5.2814
